export { default as Page } from './components/page';
export { default as ConfigProvider } from './components/ConfigContext';
export type { RichTextProps } from './components/rich-text';
export { default as RichText } from './components/rich-text';
export type { TypographyProps } from './components/typography';
export { default as Typography } from './components/typography';
export type { DividerProps } from './components/divider';
export { default as Divider } from './components/divider';
export { default as Image } from './components/image';
export { default as Grid } from './components/grid';
export { default as ProductFeed } from './components/product-feed';
declare const bizCssPrefix = "taroComp";
export { bizCssPrefix };
